exports.seed = function (knex, Promise) {
  return knex('friends').insert([
    { id: 1, name: 'Pablo Uerules', hobby: 'Horse Riding', age: 32, gender: 'Male', image: 'profile-stock-photos/pablo.jpg' },
    { id: 2, name: 'Paul Heros', hobby: 'Racketball', age: 37, gender: 'Male', image: 'profile-stock-photos/pablo.jpg' },
    { id: 3, name: 'James Udeany', hobby: 'Baking', age: 35, gender: 'Male', image: 'profile-stock-photos/peter.jpg' },
    { id: 4, name: 'Jillius Maximus', hobby: 'Horse Riding', age: 39, gender: 'Female', image: 'profile-stock-photos/ashleus.jpg' },
    { id: 5, name: 'Ashleus Orightious', hobby: 'Squash', age: 28, gender: 'Female', image: 'profile-stock-photos/jillius' },
    { id: 6, name: 'Peter Urlish', hobby: 'Horse Riding', age: 25, gender: 'Male', image: 'profile-stock-photos/paul.jpg' },
    { id: 7, name: 'Piha de Morney', hobby: 'Squash', age: 26, gender: 'Male', image: 'profile-stock-photos/piha.jpg' },
    { id: 8, name: 'Suzana Rosa', hobby: 'Tennis', age: 42, gender: 'Female', image: 'profile-stock-photos/female1.jpg' },
    { id: 9, name: 'Peach McQueen', hobby: 'Tennis', age: 21, gender: 'Gender is social construct', image: 'profile-stock-photos/female2.jpg' },
    { id: 10, name: 'Haley McFace', hobby: 'Horse Riding', age: 18, gender: 'Female', image: 'profile-stock-photos/jillius.jpg' },
    { id: 11, name: 'Ireland Baldwin', hobby: 'Tennis', age: 51, gender: 'Female', image: 'profile-stock-photos/female3.jpg' },
    { id: 12, name: 'Justin McBeiber', hobby: 'Tennis', age: 28, gender: 'Male', image: 'profile-stock-photos/piha.jpg' },
    { id: 13, name: 'Gwnyth McEggmeister', hobby: 'Walking', age: 25, gender: 'Female', image: 'profile-stock-photos/female4.jpg' },
    { id: 14, name: 'Herla Mace', hobby: 'Walking', age: 19, gender: 'Female', image: 'profile-stock-photos/female1.jpg' },
    { id: 15, name: 'Pavina Brody', hobby: 'Walking', age: 26, gender: 'Female', image: 'profile-stock-photos/female3.jpg' },
    { id: 16, name: 'Ace Bucket', hobby: 'Walking', age: 31, gender: 'Male', image: 'profile-stock-photos/peter.jpg' },
    { id: 17, name: 'Toni Eagle', hobby: 'Baking', age: 30, gender: 'Female', image: 'profile-stock-photos/peach.jpb' },
    { id: 18, name: 'Winne Bago', hobby: 'Baking', age: 21, gender: 'Female', image: 'profile-stock-photos/ashleus.jpg' },
    { id: 19, name: 'Michelle Bamao', hobby: 'Rugby', age: 32, gender: 'Female', image: 'profile-stock-photos/peach.jpg' },
    { id: 20, name: 'Donald Morse', hobby: 'Netball', age: 67, gender: 'Male', image: 'profile-stock-photos/james.jpg' },
    { id: 21, name: 'Kai Knightly', hobby: 'Hockey', age: 29, gender: 'Male', image: 'profile-stock-photos/pablo.jpg' },
    { id: 22, name: 'Leslie Haverfield', hobby: 'Football', age: 31, gender: 'Female', image: 'profile-stock-photos/female4.jpg' },
    { id: 23, name: 'Aimee Rez', hobby: 'Eating', age: 35, gender: 'Female', image: 'profile-stock-photos/peach.jpg' },
    { id: 24, name: 'Bodhi Reeves', hobby: 'Cards', age: 39, gender: 'Male', image: 'profile-stock-photos/peter.jpg' },
    { id: 25, name: 'Dylan Cole', hobby: 'Tinder', age: 18, gender: 'Gender is social construct', image: 'profile-stock-photos/piha.jpg' },
    { id: 26, name: 'Brenda Beverly', hobby: 'Gaming', age: 19, gender: 'Gender is social construct', image: 'profile-stock-photos/female3.jpg' },
    { id: 27, name: 'Rachel Ross', hobby: 'Gaming', age: 22, gender: 'Female', image: 'profile-stock-photos/female1.jpg' },
    { id: 28, name: 'Joey Chandler', hobby: 'Acting', age: 27, gender: 'Male', image: 'profile-stock-photos/james.jpg' },
    { id: 29, name: 'Les Miserable', hobby: 'Theatre', age: 40, gender: 'Male', image: 'profile-stock-photos/pablo.jpg' },
    { id: 30, name: 'Amber Pure', hobby: 'Sewing', age: 52, gender: 'Female', image: 'profile-stock-photos/suzana.jpg' }
  ])
}
